trigger:
- master

pool:
  name: default
  vmImage: ubuntu-latest

steps:
- script: echo executing script on ubuntu-latest
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'